service: opencv-serverless

custom:
  pythonRequirements:
    dockerizePip: non-linux
    noDeploy: []
  OPENCV_PROCESS_BUCKET: kriti-images-to-be-resized
  OPENCV_OUTPUT_BUCKET: kriti-resized-images

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        - arn:aws:s3:::${self:custom.OPENCV_PROCESS_BUCKET}/*
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - arn:aws:s3:::${self:custom.OPENCV_OUTPUT_BUCKET}/*
  environment:
    OPENCV_OUTPUT_BUCKET: ${self:custom.OPENCV_OUTPUT_BUCKET}

functions:
  opencv:
    handler: handler.opencv
    events:
      - s3:
          bucket: ${self:custom.OPENCV_PROCESS_BUCKET}
          event: s3:ObjectCreated:*

resources:
  Resources:

    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.OPENCV_OUTPUT_BUCKET}

plugins:
  - serverless-python-requirements
  - serverless-s3-deploy
